Add bitarray recipe
emscripten-forge/recipes pull request #1101
Opened 2024-06-07 13:31 UTC by KGB99

The tests for the bitarray still do not run. I tried to write one that runs using pytest, however i get a runtime error.

2024-06-07 13:57 UTC, IsabelParedes requested changes

2024-06-07 13:57 UTC, IsabelParedes commented on recipes/recipes_emscripten/bitarray/recipe.yaml
> +    - bitarray
`bitarray` shouldn't need to be included again here

2024-06-07 13:57 UTC, IsabelParedes commented on recipes/recipes_emscripten/bitarray/recipe.yaml
> +    - run_test.py
Could you rename this file to `test_bitarray.py` for consistency?

2024-06-07 13:57 UTC, IsabelParedes commented on recipes/recipes_emscripten/bitarray/run_test.py
> +import bitarray
Could you move the import inside the function?

2024-06-07 13:57 UTC, IsabelParedes commented on recipes/recipes_emscripten/bitarray/run_test.py
> +import pytest
`pytest` shouldn't be needed here

2024-06-10 09:35 UTC, DerThorsten commented
I believe this error of the missing file  '/lib/python3.11/site-packages/bitarray/test_150.pickle' might be due to the filtering in empack. We are currently fixing this with https://github.com/emscripten-forge/empack/pull/98

2024-06-18 07:20 UTC, DerThorsten approved these changes

2024-06-18 10:12 UTC, IsabelParedes approved these changes

2024-06-18 10:36 UTC, merged