WIP: Add Abseil-cpp
emscripten-forge/recipes pull request #1118
Opened 2024-06-13 13:03 UTC by KGB99

2024-06-14 09:15 UTC, KGB99 commented
i believe this should work as soon as #1120 is merged

2024-06-14 14:09 UTC, IsabelParedes requested changes

2024-06-14 14:09 UTC, IsabelParedes commented on recipes/recipes_emscripten/abseil-cpp/recipe.yaml
> +    - KGB9
Tiny typo

2024-06-14 14:09 UTC, IsabelParedes commented on recipes/recipes_emscripten/abseil-cpp/recipe.yaml
> +  name: abseil-split
Since it's only one package, let's rename it to `libabseil`, the directory name as well.

2024-06-17 12:09 UTC, IsabelParedes approved these changes

2024-06-17 18:54 UTC, merged