Added recipes for curl (libcurl-static)
emscripten-forge/recipes pull request #1332
Opened 2024-09-24 08:29 UTC by anutosh491

2024-09-24 08:30 UTC, anutosh491 commented
Need to 
1) Add tests
2) look into the required configuration flags (a couple might be unncessary)

2024-09-24 08:46 UTC, anutosh491 commented
I did this for supporting magics in xeus-cpp but thinking about it, having `libcurl` would help us compile `RCurl` R package (cc @IsabelParedes might be interested here)

2024-09-24 13:01 UTC, IsabelParedes requested changes

2024-09-24 13:01 UTC, IsabelParedes commented on recipes/recipes_emscripten/curl/recipe.yaml
> +  - script: test -f $PREFIX/lib/libcurl.a
There's another way to check for package contents which is a bit faster but his is optional. See https://prefix-dev.github.io/rattler-build/latest/reference/recipe_file/#check-for-package-contents

2024-09-24 13:16 UTC, DerThorsten commented
curl will not work in the browser.

2024-09-24 13:25 UTC, anutosh491 commented
> curl will very likely not work in the browser (tempted to close this PR)

I had my doubts but then I saw curl being used in wasm at few resources

1) https://curl.se/download.html (its through wasix, so search for wasix)
2) https://github.com/wapm-packages/curl
3) https://github.com/curl/curl/issues/13018#issuecomment-2045699712

For the xeus-cpp use case, even if we can catch hold of the `include/curl.h` file it would do, so i thought of raising it.

2024-09-24 14:40 UTC, DerThorsten commented
> > curl will very likely not work in the browser (tempted to close this PR)
> 
> I had my doubts but then I saw curl being used in wasm at few resources
> 
> 1. https://curl.se/download.html (its through wasix, so search for wasix)
> 2. https://github.com/wapm-packages/curl
> 3. [Duplicate symbols when compiling for wasm with emscripten curl/curl#13018 (comment)](https://github.com/curl/curl/issues/13018#issuecomment-2045699712)
> 
> And the xeus-cpp use case was just blocked since a while so I thought of raising it and this recipe is only for `libcurl-static` (not for the other 2 components which are `curl` and `libcurl`). Let me know what you think.

So while compiling curl is possible I doubt that anything meaningful will work for **the browser**.
This can work for wasi  / wasix or other platforms when they emulate the appropriate syscalls, but in the browser you will need to use **async** APIs for downloading things (ie the fetch API  ). 
If there is no dedicated code **in the curl codebase** to handle emscripten, this **will not work** to download things

2024-09-24 14:48 UTC, anutosh491 commented
Thanks for the explanation here @tharun571 why exactly do we use curl in xeus-cpp. Cause I guess the above confirms we might not be able to use it.

2024-09-24 14:56 UTC, tharun571 commented
@anutosh491 I am using curl to call the LLMs in xeus-cpp. As mentioned above, fetch API might be something I will try for our project.

2024-10-04 05:24 UTC, anutosh491 commented
Closing as won't work.

2024-10-04 05:24 UTC, closed without merging