Fix bump_recipes_version and some recipes
emscripten-forge/recipes pull request #324
Opened 2023-04-21 15:30 UTC by martinRenou

2023-04-21 15:45 UTC, martinRenou commented
@DerThorsten I'm getting `emmake: error: config file not found: /home/runner/work/recipes/recipes/emsdk/upstream/emscripten/.emscripten.  Please create one by hand or run emcc --generate-config`, but I'm doing so in my latest commit. Do you know what could be wrong here?

2023-04-21 15:53 UTC, DerThorsten commented
> @DerThorsten I'm getting `emmake: error: config file not found: /home/runner/work/recipes/recipes/emsdk/upstream/emscripten/.emscripten. Please create one by hand or run emcc --generate-config`, but I'm doing so in my latest commit. Do you know what could be wrong here?

https://github.com/emscripten-forge/recipes/pull/325 this might do the trick

2023-04-21 16:00 UTC, DerThorsten commented
with #325 merged this should work

2023-04-26 09:09 UTC, jtpio commented
Thanks!

Looks like it should fine to merge and try the script again?

2023-04-26 09:15 UTC, DerThorsten requested changes

2023-04-26 09:15 UTC, DerThorsten commented on recipes/recipes_emscripten/arrow-python/recipe.yaml
I think we need to update the build number here

2023-04-26 09:15 UTC, DerThorsten commented on recipes/recipes_emscripten/arrow-python/recipe.yaml
at least the CI will try to upload this package with a build number / version which already exists

2023-04-26 09:15 UTC, DerThorsten commented on recipes/recipes_emscripten/clapack/recipe.yaml
probably also need to increment build number

2023-04-26 09:15 UTC, DerThorsten commented on recipes/recipes_emscripten/openssl/recipe.yaml
build number?

2023-04-26 09:16 UTC, martinRenou commented on recipes/recipes_emscripten/libffi/recipe.yaml
> -    - sel(unix or emscripten): '{{ compiler("cxx") }}'
this was resolved already

2023-04-26 09:21 UTC, martinRenou commented
thks

2023-04-26 09:30 UTC, DerThorsten approved these changes

2023-04-26 09:44 UTC, merged